# @package _global_
defaults:
  - /runner/default_hkkim_a100_gpu2

runner:
  checkpointing_steps: 5000
  validation_steps: 2500
  lr_scheduler: constant_with_warmup
  enable_xformers_memory_efficient_attention: true
